# Generated by Django 2.1.7 on 2019-02-22 23:10

import django.core.validators
from django.db import migrations, models
import social_match.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_standing',
            field=models.CharField(choices=[('1st', 'First Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4th', 'Fourth Year'), ('5th', 'Graduate')], default='1st', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2023, validators=[social_match.models.min_value_current_year, social_match.models.max_value_in_four_years]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+??\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
