# Generated by Django 2.1.7 on 2019-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date posted'),
        ),
    ]
