# Generated by Django 2.1.7 on 2019-03-05 05:13

from django.db import migrations
from django.core.management import call_command
import os

def load_classes_fixture(apps, schema_editor):
    fixture = 'class_data'
    call_command('loaddata', fixture, app_label='social_match')


def unload_classes_fixture(apps, schema_editor):
    Course = apps.get_model("social_match", "Course")
    Course.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0002_post'),
    ]

    operations = [
        migrations.RunPython(load_classes_fixture, reverse_code=unload_classes_fixture),
    ]
