# Generated by Django 2.1.7 on 2019-03-09 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0003_auto_20190309_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date edited'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_edited',
            field=models.BooleanField(default=False),
        ),
    ]
