# Generated by Django 2.1.7 on 2019-02-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0003_auto_20190222_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(blank=True, to='social_match.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='social_match.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, to='social_match.Interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(blank=True, to='social_match.Major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='minors',
            field=models.ManyToManyField(blank=True, to='social_match.Minor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='social_match.Skill'),
        ),
    ]
