# Generated by Django 2.1.7 on 2019-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0004_auto_20190309_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date edited'),
        ),
    ]
