# Generated by Django 2.1.7 on 2019-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0005_auto_20190309_0231'),
        ('social_match', '0003_classes_majors_minors'),
    ]

    operations = [
    ]
