# Generated by Django 2.1.7 on 2019-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0005_auto_20190309_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='minor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
