# Generated by Django 2.1.7 on 2019-03-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0007_comment'),
        ('social_match', '0003_classes_majors_minors'),
    ]

    operations = [
    ]
