# Generated by Django 2.1.1 on 2019-03-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0006_auto_20190320_1031'),
        ('social_match', '0008_merge_20190321_0139'),
    ]

    operations = [
    ]
