# Generated by Django 2.1.1 on 2019-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0010_auto_20190325_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
