# Generated by Django 2.1.7 on 2019-04-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0003_auto_20190402_2043'),
        ('social_match', '0011_auto_20190401_1622'),
    ]

    operations = [
    ]
