# Generated by Django 2.1.7 on 2019-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_match', '0012_merge_20190403_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
